# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diana.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diana.proto',
  package='diana',
  serialized_pb='\n\x0b\x64iana.proto\x12\x05\x64iana\"\xbf\x01\n\x0eMessageWrapper\x12\x36\n\x0bMessageType\x18\x01 \x02(\x0e\x32!.diana.MessageWrapper.messageType\x12!\n\x08HelloMsg\x18\x02 \x01(\x0b\x32\x0f.diana.helloMsg\x12)\n\x0cPhysPropsMsg\x18\x03 \x01(\x0b\x32\x13.diana.physPropsMsg\"\'\n\x0bmessageType\x12\t\n\x05HELLO\x10\x02\x12\r\n\tPHYSPROPS\x10\x03\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"\x1f\n\x08helloMsg\x12\x13\n\x04name\x18\x01 \x01(\t:\x05HELLO\"\xca\x01\n\x0cphysPropsMsg\x12\x17\n\x04name\x18\x01 \x01(\t:\tPHYSPROPS\x12\x0c\n\x04mass\x18\x02 \x02(\x01\x12\x1f\n\x08position\x18\x03 \x02(\x0b\x32\r.diana.Vector\x12\x1f\n\x08velocity\x18\x04 \x02(\x0b\x32\r.diana.Vector\x12\"\n\x0borientation\x18\x05 \x02(\x0b\x32\r.diana.Vector\x12\x1d\n\x06thrust\x18\x06 \x02(\x0b\x32\r.diana.Vector\x12\x0e\n\x06radius\x18\x07 \x02(\x01')



_MESSAGEWRAPPER_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='messageType',
  full_name='diana.MessageWrapper.messageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HELLO', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHYSPROPS', index=1, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=175,
  serialized_end=214,
)


_MESSAGEWRAPPER = _descriptor.Descriptor(
  name='MessageWrapper',
  full_name='diana.MessageWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MessageType', full_name='diana.MessageWrapper.MessageType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HelloMsg', full_name='diana.MessageWrapper.HelloMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PhysPropsMsg', full_name='diana.MessageWrapper.PhysPropsMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGEWRAPPER_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=214,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='diana.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='diana.Vector.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='diana.Vector.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='diana.Vector.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=257,
)


_HELLOMSG = _descriptor.Descriptor(
  name='helloMsg',
  full_name='diana.helloMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='diana.helloMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("HELLO", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=259,
  serialized_end=290,
)


_PHYSPROPSMSG = _descriptor.Descriptor(
  name='physPropsMsg',
  full_name='diana.physPropsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='diana.physPropsMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("PHYSPROPS", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mass', full_name='diana.physPropsMsg.mass', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='diana.physPropsMsg.position', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='diana.physPropsMsg.velocity', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='diana.physPropsMsg.orientation', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thrust', full_name='diana.physPropsMsg.thrust', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='radius', full_name='diana.physPropsMsg.radius', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=293,
  serialized_end=495,
)

_MESSAGEWRAPPER.fields_by_name['MessageType'].enum_type = _MESSAGEWRAPPER_MESSAGETYPE
_MESSAGEWRAPPER.fields_by_name['HelloMsg'].message_type = _HELLOMSG
_MESSAGEWRAPPER.fields_by_name['PhysPropsMsg'].message_type = _PHYSPROPSMSG
_MESSAGEWRAPPER_MESSAGETYPE.containing_type = _MESSAGEWRAPPER;
_PHYSPROPSMSG.fields_by_name['position'].message_type = _VECTOR
_PHYSPROPSMSG.fields_by_name['velocity'].message_type = _VECTOR
_PHYSPROPSMSG.fields_by_name['orientation'].message_type = _VECTOR
_PHYSPROPSMSG.fields_by_name['thrust'].message_type = _VECTOR
DESCRIPTOR.message_types_by_name['MessageWrapper'] = _MESSAGEWRAPPER
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['helloMsg'] = _HELLOMSG
DESCRIPTOR.message_types_by_name['physPropsMsg'] = _PHYSPROPSMSG

class MessageWrapper(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEWRAPPER

  # @@protoc_insertion_point(class_scope:diana.MessageWrapper)

class Vector(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VECTOR

  # @@protoc_insertion_point(class_scope:diana.Vector)

class helloMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLOMSG

  # @@protoc_insertion_point(class_scope:diana.helloMsg)

class physPropsMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHYSPROPSMSG

  # @@protoc_insertion_point(class_scope:diana.physPropsMsg)


# @@protoc_insertion_point(module_scope)
