name: Unisim headers and binaries
# May want to consider reusable workflows here
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Also signing bot commits is irritating, but can be done
# - https://github.com/Nautilus-Cyberneering/pygithub/blob/main/docs/how_to_sign_automatic_commits_in_github_actions.md

on:
  push:
    branches: ["*"]
    paths: ["unisim"]
  pull_request:
    branches: ["*"]
    paths: ["unisim"]

jobs:
  build-headers:
    name: Build unisim headers
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Build headers
        run: |
          cd unisim/unisim
          make unisim-headers

      - name: Uploader headers artifact
        uses: actions/upload-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/*.hpp
          retention-days: 1

  build-linux-binary:
    name: Build unisim linux amd64 binary
    runs-on: ubuntu-latest
    timeout-minutes: 2

    needs:
      - build-headers
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      - name: Build linux binary
        run: |
          cd unisim/unisim
          make unisim-bin

      - name: Uploader unisim linux binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: unisim-linux-amd64
          path: unisim/unisim/bin/unisim
          retention-days: 1

  build-windows-binary:
    name: Build unisim Windows Release amd64 binary
    runs-on: windows-latest
    timeout-minutes: 5

    needs:
      - build-headers

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Download headers artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      - name: Setup msbuild
        if: github.ref == 'refs/heads/master'
        uses: microsoft/setup-msbuild@v1

      - name: Build Windows binary
        if: github.ref == 'refs/heads/master'
        run: |
          cd unisim
          msbuild unisim.sln /p:Configuration=Release

      - name: Uploader unisim Windows binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: unisim-windows-release-amd64
          path: unisim/x64/Release/unisim.exe
          retention-days: 1

  commit-assets:
    name: Commit headers and binaries
    runs-on: ubuntu-latest
    needs:
      - build-linux-binary
      - build-windows-binary
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      - name: Download linux binary
        uses: actions/download-artifact@v3
        with:
          name: unisim-linux-amd64
          path: unisim/unisim/bin/

      - name: Download windows binary
        uses: actions/download-artifact@v3
        with:
          name: unisim-windows-release-amd64
          path: unisim/x64/Release/

      - name: Commit windows binary
        run: |
          git config --global user.name 'Diana Actions'
          git config --global user.email 'diana-actions@flyingfortressit.ca'
          git commit -am "ACTION: Updating unisim headers and binaries"
          git push
