name: Unisim headers and binaries
# May want to consider reusable workflows here
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Also signing bot commits is irritating, but can be done
# - https://github.com/Nautilus-Cyberneering/pygithub/blob/main/docs/how_to_sign_automatic_commits_in_github_actions.md

on:
  push:
    branches: ["*"]
    paths: ["unisim"]
  pull_request:
    branches: ["*"]

jobs:
  build-headers:
    name: Build unisim headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build headers
        run: |
          cd unisim/unisim
          make unisim-headers

      - uses: actions/upload-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/*.hpp

      # - name: Commit headers
      #   run: |
      #     git config --global user.name 'Diana Actions'
      #     git config --global user.email 'diana-actions@flyingfortressit.ca'
      #     git commit -am "ACTION: Udating unisim headers"
      #     git push

  # build-linux-binary:
  #   name: Build unisim linux amd64 binary
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-headers
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     # - name: Git pull
  #     #   run: git pull

  #     - name: Build linux binary
  #       run: |
  #         cd unisim/unisim
  #         make unisim-bin

  #     - name: Commit linux binary
  #       run: |
  #         git config --global user.name 'Diana Actions'
  #         git config --global user.email 'diana-actions@flyingfortressit.ca'
  #         git commit -am "ACTION: Udating unisim linux amd64 binary"
  #         git push

  # build-windows-binary:
  #   name: Build unisim Windows Release amd64 binary
  #   runs-on: windows-latest
  #   if: github.ref == 'refs/heads/master'
  #   needs:
  #     - build-headers
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Git pull
  #       run: git pull

  #     - name: Setup msbuild
  #       uses: microsoft/setup-msbuild@v1

  #     - name: Build Windows binary
  #       run: |
  #         cd unisim
  #         msbuild unisim.sln /p:Configuration=Release

  #     - name: Commit windows binary
  #       run: |
  #         git config --global user.name 'Diana Actions'
  #         git config --global user.email 'diana-actions@flyingfortressit.ca'
  #         git commit -am "ACTION: Udating unisim Windows Release-x64 binary"
  #         git push
