name: Unisim headers and binaries
# May want to consider reusable workflows here
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# Also signing bot commits is irritating, but can be done
# - https://github.com/Nautilus-Cyberneering/pygithub/blob/main/docs/how_to_sign_automatic_commits_in_github_actions.md

on:
  push:
    branches: ["**/build-unisim"]
    paths: ["unisim/**"]
  pull_request:
    branches: ["*"]
    paths: ["unisim/**"]

jobs:
  build-headers:
    name: Build unisim headers
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Build headers
        run: |
          cd unisim/unisim
          make unisim-headers

      - name: Uploader headers artifact
        uses: actions/upload-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/*.hpp
          retention-days: 1

  build-linux-binary:
    name: Build unisim linux amd64 binary
    runs-on: ubuntu-latest
    timeout-minutes: 2

    needs:
      - build-headers
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      - name: Build linux binary
        run: |
          cd unisim/unisim
          make unisim-bin

      - name: Uploader unisim linux binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: unisim-linux-amd64
          path: unisim/unisim/bin/unisim
          retention-days: 1

  # For commits to master, or on a PR, build the windows binary
  build-windows-binary:
    name: Build unisim Windows Release amd64 binary
    runs-on: windows-latest
    timeout-minutes: 5
    if: ${{ (github.event_name == 'pull_request') || (github.ref == 'refs/heads/master') }}

    needs:
      - build-headers

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout branch
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Windows binary
        run: |
          cd unisim
          msbuild unisim.sln /p:Configuration=Release

      - name: Uploader unisim Windows binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: unisim-windows-release-amd64
          path: unisim/x64/Release/unisim.exe
          retention-days: 1

  # If the trigger is not a PR, and the branch is not master, skip building a new Windows binary
  # and just upload the in-tree one as the artifact for use later.
  skip-build-windows-binary:
    name: Upload in-tree unisim Windows Release amd64 binary
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ (github.event_name != 'pull_request') && (github.ref != 'refs/heads/master') }}

    needs:
      - build-headers

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Uploader unisim Windows binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: unisim-windows-release-amd64
          path: unisim/x64/Release/unisim.exe
          retention-days: 1

  commit-assets:
    name: Commit headers and binaries
    runs-on: ubuntu-latest
    # Always run, just do so after all of the builds.
    if: ${{ always() }}
    needs:
      - build-linux-binary
      - build-windows-binary
      - skip-build-windows-binary
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          path: unisim/unisim/src/include/

      # Should astyle the repo here too.
      # astyle -j --style=ansi --suffix=none --keep-one-line-blocks \
      #   --recursive "./*hpp" "./*cpp" "./*c" "./*h"

      - name: Download linux binary
        uses: actions/download-artifact@v3
        with:
          name: unisim-linux-amd64
          path: unisim/unisim/bin/

      - name: Download windows binary
        uses: actions/download-artifact@v3
        with:
          name: unisim-windows-release-amd64
          path: unisim/x64/Release/

      - name: Commit windows binary
        run: |
          git config --global user.name 'Diana Actions'
          git config --global user.email 'diana-actions@flyingfortressit.ca'
          git commit -am "ACTION: Updating unisim headers and binaries"
          git push
